### ISSUE TITLE
Sheets v4 API Upgrade

### ISSUE THREAD

**Issue by endel** [terence410/array-to-google-sheets#1]
Hi @terence410, I've been using your library for 1+ years, and it's been working wonders for me.

I've received an email a while back from Google saying that the Sheets v3 API is going to be retired on March 3, 2020.

Here are the issues of the `google-spreadsheet` dependency tracking this:
- https://github.com/theoephraim/node-google-spreadsheet/issues/193
- https://github.com/theoephraim/node-google-spreadsheet/issues/246

I'm not sure if the v4 API will allow to perform the operation you do here with `array-to-google-sheets`. I'd like to contribute fixing this if possible, as I rely on this library for a "indie" commercial product I've built with it

Cheers!

**Comment by terence410** [comment]
thx for the update. I will take a look and get back to you.

Meanwhile, if you want any extra features on this package, pls also let me know

**Comment by terence410** [comment]
I checked the node-google-spreadsheet, I saw that he has plan to upgrade to v4. i will update and test this package again once he got any updates.

**Comment by terence410** [comment]
https://www.npmjs.com/package/array-to-google-sheets

I have rewritten the entire library using Google Sheets v4 API.

**Comment by endel** [comment]
That's great news @terence410, thank you so much for this! ❤️ 

Gonna check it out soon!
