### ISSUE TITLE
Support array of objects as input

### ISSUE THREAD

**Issue by iudex-** [terence410/array-to-google-sheets#2]
Hey, thanks a lot for this handy library! 

Would you be open to accepting an array of objects as input?
The use case being dumping the result of some mongodb query into a spreadsheet with ease.

Either by handling an updated type, ie: `export type IRow = (ICell | object)[];` instead of `export type IRow = ICell[];`
or alternatively by overloading `updateSheet` with `updateSheet(name: string, values: object[], ...)` :thinking:

I basically build this already on top of your library but would contribute a PR if you point out the way you imagine it.

This is what I'm currently doing before passing data to `updateSheet`:
```js
const arrayobjects2arrayarrays = (arrayOfObjects, { keysAsHeader = true, replacer }) => {
  const keys = Array.from(new Set(arrayOfObjects.map(obj => Object.keys(obj)).flat())); // get all uninque keys as array
  const data = arrayOfObjects.map(obj => keys.map(key => (replacer ? replacer(obj[key]) : obj[key])));   // convert all objects to arrays and call replacer on each value, if provided
  return [keysAsHeader ? keys : [], ...data];
};
```

**Comment by terence410** [comment]
you may try to take a look on exportAsObjectSheet callback. But you have to preset some columns in the sheet before using that. 

I know it may not be what you want, but having able to pass objects already a bit making the library too dynamic to use and hard to predict it's behavior. I think it will be good to keep your own way to solve such problem.

**Comment by iudex-** [comment]
Hm, yeah, i looks like `ObjectSheet` could be used like this:
https://github.com/terence410/array-to-google-sheets/blob/89d6102cdb2fefe268f38df853b1981268686a63/.sample.ts#L82-L100

With [`objectSheet.append(...)`](https://github.com/terence410/array-to-google-sheets/blob/c66e973f27db1443fc2896d6d8d777bfb332d5f6/src/ObjectSheet.ts#L89) instead of `objectSheet.get()`

But it doesn't appear to support batch updates (yet? :slightly_smiling_face: ), i'll have to stick with the original solution. 

Thanks for the clarification!
