### ISSUE TITLE
resize() moves the sheet

### ISSUE THREAD

**Issue by iudex-** [terence410/array-to-google-sheets#3]
Whenever `resize` is being called, eg. by setting `fitToSize=true` or the updated sheet not being big enough, the updated sheet is moved to the left most position 
![Peek 2020-10-21 10-37](https://user-images.githubusercontent.com/56843/96696460-147c3b80-138b-11eb-8a6a-99733e7d1e79.gif)

I only ever noticed this since moving from v1.0.1 to v2.1.6

Do you see any chance to fix this or it's just the way the sheets api behaves now?

**Comment by terence410** [comment]
I am checking on it. get back you soon

**Comment by terence410** [comment]
this is fixed in the latest version.

**Comment by iudex-** [comment]
Thank you so much! :relaxed:
